// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Chocachoca.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____Chocachoca_h__
#define ____Chocachoca_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompChocachoca
{

class Chocachoca;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompChocachoca::Chocachoca>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompChocachoca::Chocachoca*);

}

}

namespace RoboCompChocachoca
{

class Chocachoca;
bool operator==(const Chocachoca&, const Chocachoca&);
bool operator<(const Chocachoca&, const Chocachoca&);
::Ice::Object* upCast(::RoboCompChocachoca::Chocachoca*);
typedef ::IceInternal::Handle< ::RoboCompChocachoca::Chocachoca> ChocachocaPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompChocachoca::Chocachoca> ChocachocaPrx;
void __patch(ChocachocaPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompChocachoca
{

class Callback_Chocachoca_go_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Chocachoca_go_Base> Callback_Chocachoca_goPtr;

class Callback_Chocachoca_turn_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Chocachoca_turn_Base> Callback_Chocachoca_turnPtr;

class Callback_Chocachoca_stop_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Chocachoca_stop_Base> Callback_Chocachoca_stopPtr;

class Callback_Chocachoca_getState_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Chocachoca_getState_Base> Callback_Chocachoca_getStatePtr;

}

namespace IceProxy
{

namespace RoboCompChocachoca
{

class Chocachoca : virtual public ::IceProxy::Ice::Object
{
public:

    void go(::Ice::Float x, ::Ice::Float z)
    {
        go(x, z, 0);
    }
    void go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx)
    {
        go(x, z, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_go(x, z, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(x, z, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_go(x, z, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(x, z, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z)
    {
        return begin_go(x, z, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx)
    {
        return begin_go(x, z, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::RoboCompChocachoca::Callback_Chocachoca_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::RoboCompChocachoca::Callback_Chocachoca_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, &__ctx, __del, __cookie);
    }

    void end_go(const ::Ice::AsyncResultPtr&);
    
private:

    void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void turn(::Ice::Float speed)
    {
        turn(speed, 0);
    }
    void turn(::Ice::Float speed, const ::Ice::Context& __ctx)
    {
        turn(speed, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_turn(speed, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_turn(speed, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_turn(speed, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_turn(speed, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed)
    {
        return begin_turn(speed, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx)
    {
        return begin_turn(speed, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::RoboCompChocachoca::Callback_Chocachoca_turnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::RoboCompChocachoca::Callback_Chocachoca_turnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, &__ctx, __del, __cookie);
    }

    void end_turn(const ::Ice::AsyncResultPtr&);
    
private:

    void turn(::Ice::Float, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_turn(::Ice::Float, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void stop()
    {
        stop(0);
    }
    void stop(const ::Ice::Context& __ctx)
    {
        stop(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_stop(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stop(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stop(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stop(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stop(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_stop()
    {
        return begin_stop(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx)
    {
        return begin_stop(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::RoboCompChocachoca::Callback_Chocachoca_stopPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx, const ::RoboCompChocachoca::Callback_Chocachoca_stopPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(&__ctx, __del, __cookie);
    }

    void end_stop(const ::Ice::AsyncResultPtr&);
    
private:

    void stop(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void getState()
    {
        getState(0);
    }
    void getState(const ::Ice::Context& __ctx)
    {
        getState(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getState(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_getState(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_getState(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getState(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getState(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_getState(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getState(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getState(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_getState()
    {
        return begin_getState(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& __ctx)
    {
        return begin_getState(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::RoboCompChocachoca::Callback_Chocachoca_getStatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& __ctx, const ::RoboCompChocachoca::Callback_Chocachoca_getStatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(&__ctx, __del, __cookie);
    }

    void end_getState(const ::Ice::AsyncResultPtr&);
    
private:

    void getState(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_secure(bool __secure) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_twoway() const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_oneway() const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_batchOneway() const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_datagram() const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_batchDatagram() const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_compress(bool __compress) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Chocachoca> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Chocachoca*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompChocachoca
{

class Chocachoca : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void getState(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompChocachoca
{

class Chocachoca : virtual public ::IceDelegate::RoboCompChocachoca::Chocachoca,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void getState(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompChocachoca
{

class Chocachoca : virtual public ::IceDelegate::RoboCompChocachoca::Chocachoca,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void getState(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompChocachoca
{

class Chocachoca : virtual public ::Ice::Object
{
public:

    typedef ChocachocaPrx ProxyType;
    typedef ChocachocaPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___go(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void turn(::Ice::Float, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___turn(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void stop(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___stop(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getState(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getState(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Chocachoca& l, const Chocachoca& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Chocachoca& l, const Chocachoca& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompChocachoca
{

template<class T>
class CallbackNC_Chocachoca_go : public Callback_Chocachoca_go_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Chocachoca_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_go<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_go<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_go<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_go<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Chocachoca_go : public Callback_Chocachoca_go_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Chocachoca_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_go<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_goPtr
newCallback_Chocachoca_go(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_go<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Chocachoca_turn : public Callback_Chocachoca_turn_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Chocachoca_turn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_turn<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_turn<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_turn<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_turn<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Chocachoca_turn : public Callback_Chocachoca_turn_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Chocachoca_turn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_turn<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_turn<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_turn<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_turnPtr
newCallback_Chocachoca_turn(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_turn<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Chocachoca_stop : public Callback_Chocachoca_stop_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Chocachoca_stop(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_stop<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_stop<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_stop<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_stop<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Chocachoca_stop : public Callback_Chocachoca_stop_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Chocachoca_stop(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_stop<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_stop<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_stop<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_stopPtr
newCallback_Chocachoca_stop(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_stop<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Chocachoca_getState : public Callback_Chocachoca_getState_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Chocachoca_getState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_getState<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_getState<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_getState<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Chocachoca_getState<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Chocachoca_getState : public Callback_Chocachoca_getState_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Chocachoca_getState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_getState<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_getState<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_getState<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Chocachoca_getStatePtr
newCallback_Chocachoca_getState(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Chocachoca_getState<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
